name: Delete branch folder from AWS S3 bucket

on:
  pull_request:
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: Delete branch folder in AWS S3 bucket
      run: |
        echo "Deleting folder for branch ${{github.head_ref}}"
        ./scripts/delete-bucket.sh
      env:
        branch_name: ${{github.head_ref}}




  
