# This is a basic workflow to help you get started with Actions

name: delete a branch, delete s3 directory

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Configure AWS credentials from Test account
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-southeast-1
    - name: check branch
      run: |
        echo "github.head_ref ${{github.head_ref}}"
        echo "github.base_ref ${{github.base_ref}}"
        echo "github.head_ref_edit ${{github.head_ref}}"
        echo "github.base_ref_edit ${{github.base_ref}}"
    - name: run script
      run: ./scripts/delete.sh




  
