name: Build and Deploy to feature to AWS S3 bucket

on:
  pull_request:
  # if the event type is pull_request,
  # the 'branches' config refers to the target branch
    branches:
    - 'master'
    paths:
    - 'packages/stencil-components/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: ref
      run: echo "YO ${GITHUB_REF}"
    - name: ref
      run: echo pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
    - name: ref
      run: echo $pull_number
    - name: Install lerna
      run: npm install -g lerna
    - name: Run lerna bootstrap
      run: lerna bootstrap
    - name: Build
      run: |
        echo "Building from branch ${GITHUB_REF##*/}..."
        npm run build
      working-directory: packages/stencil-components
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "packages/stencil-components/www"
        DEST_DIR: ${GITHUB_REF##*/}
      
