# This is a basic workflow to help you get started with Actions

name: publish to s3 master

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
    - master
    paths:
    - 'packages/stencil-components/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install lerna
      run: npm install -g lerna
    - name: Run lerna bootstrap
      run: lerna bootstrap
    - name: Build
      run: |
        echo "Building from branch ${GITHUB_REF##*/}..."
        npm run build
      working-directory: packages/stencil-components
    - name: Deploy to S3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read
      env:
        AWS_S3_BUCKET: ${{ secrets.AWS_BUCKET_NAME }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}
        SOURCE_DIR: "packages/stencil-components/www"
      
