# This is a basic workflow to help you get started with Actions

name: Publish to github packages

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ placeholder ]
  pull_request:
    branches: [ placeholder ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@davidlam-yc'
    - run: echo "//npm.pkg.github.com/:_authToken=${GITHUB_TOKEN}" > .npmrc
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: npm install
    - run: npm run bootstrap
    - run: npm run publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}