
name: Deploy to dev
on:
  repository_dispatch:
    types: manual-test-2
jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]
        
    steps:
    
    - name: print branch
      run: |
        echo Checking out ${{ github.event.client_payload.branch }}
    - uses: actions/checkout@v1
      with:
        ref: ${{ github.event.client_payload.branch }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm i
      run: |
        npm i
    - name: lerna bootstrap
      run: |
        npm run bootstrap
    - name: build
      run: |
        npm run build
    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: stencil-components-www
        path: packages/stencil-components/www/

